version: '3.8'

networks:
  transcendence:

services:
  front:
    container_name: front
    build: front/
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on: [postgres, back]
    ports: [80:80]
    volumes: [./front/volume:/var/www/html]
    networks: [transcendence]
    restart: on-failure
  back:
    container_name: back
    build: back/
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on: [postgres]
    ports: [3001:3001]
    networks: [transcendence]
    volumes: [./back/volume:/var/www/html]
    restart: on-failure
  postgres:
    container_name: postgres
    image: postgres
    ports: [5432:5432]
    networks: [transcendence]
    restart: always
    env_file: .env
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - .env
    networks: [transcendence]
